"""
intent_schema.py
================

SINGLE SOURCE OF TRUTH for all AgniAI intent formation business rules.

This module contains all domain-specific data structures, enumerations, and
mappings that were previously hardcoded across admin_intent.py. By centralizing
this configuration, we ensure:

1. Deterministic intent formation
2. Easy maintenance and updates
3. Consistency across the pipeline
4. Version-controlled schema changes

All modules that need business data MUST import from here, NOT hardcode lists.
"""

from __future__ import annotations

from typing import Any, Dict, FrozenSet, List, Optional, Set, Tuple

# =============================================================================
# CATEGORIES (OFFICIAL DOMAINS)
# =============================================================================

OFFICIAL_CATEGORIES: FrozenSet[str] = frozenset(
    [
        "Performance",
        "Leave",
        "Medical",
        "Attendance",
        "Strength",
        "Verification",
        "Equipment",
        "Distribution",
        "Skills",
        "Overall",
        "Schedule",
        "personaldetail",
        "disqualified",
    ]
)

# =============================================================================
# OPERATIONS (BY CATEGORY)
# =============================================================================

OPERATIONS_BY_CATEGORY: Dict[str, FrozenSet[str]] = {
    "Performance": frozenset(
        [
            "Top",
            "Bottom",
            "Improvement",
            "Drop",
            "Grading",
            "GradingSummary",
            "Average",
            "AttemptWise",
            "BestAttempt",
            "Trend",
        ]
    ),
    "Leave": frozenset(
        [
            "Most",
            "Least",
            "Current",
            "Absconded",
            "Threshold",
        ]
    ),
    "Medical": frozenset(
        [
            "BMI",
            "BloodGroup",
            "Disease",
            "Individual",
        ]
    ),
    "Attendance": frozenset(
        [
            "Monthly",
            "Weekly",
            "Daily",
            "Present",
            "Summary",
        ]
    ),
    "Strength": frozenset(
        [
            "StrengthBreakdown",
        ]
    ),
    "Verification": frozenset(
        [
            "Pending",
            "Sent",
            "NotResponded",
            "Completed",
            "Rejected",
        ]
    ),
    "Equipment": frozenset(
        [
            "Stats",
            "ByName",
            "Returned",
            "Holding",
            "AgniveerWise",
        ]
    ),
    "Distribution": frozenset(
        [
            "Latest",
            "ByUnit",
            "Unassigned",
            "TopUnit",
        ]
    ),
    "Skills": frozenset(
        [
            "BySport",
            "ByClass",
        ]
    ),
    "Overall": frozenset(
        [
            "OverallPerformance",
        ]
    ),
    "Schedule": frozenset(
        {"bytoday", "byagniveer", "bycompany", "bydate"}
    ),
    "personaldetail": frozenset(["info"]),
    "disqualified": frozenset(["removed"]),
}

# =============================================================================
# RESPONSE TYPES
# =============================================================================

RESPONSE_TYPES: FrozenSet[str] = frozenset(
    [
        "Summary",
        "Detailed",
    ]
)

RESPONSE_TYPE_DEFAULT: Optional[str] = "Summary"

# Categories that default to Detailed responses even without an explicit
# "detail" keyword in the query (leave, medical, and equipment data are
# expected to be shown in full by default).
DEFAULT_DETAILED_CATEGORIES: FrozenSet[str] = frozenset(
    [
        "Leave",
        "Medical",
        "Equipment",
    ]
)

# =============================================================================
# REQUIRED ENTITIES
# =============================================================================

# Categories where every operation targets one specific agniveer, so
# agniveerNo must be supplied (e.g. personal detail lookups).
AGNIVEER_NO_ALWAYS_REQUIRED_CATEGORIES: FrozenSet[str] = frozenset(
    [
        "personaldetail",
    ]
)

# Categories where agniveerNo is required except for the listed operations,
# which are aggregate/company-wide and don't target one person.
AGNIVEER_NO_REQUIRED_EXCEPT_OPERATIONS: Dict[str, FrozenSet[str]] = {
    "Attendance": frozenset(["Present"]),
}

# Keywords that trigger Detailed response type
DETAILED_KEYWORDS: FrozenSet[str] = frozenset(
    [
        "detail",
        "detailed",
        "complete",
        "full report",
        "complete report",
        "comprehensive",
        "everything",
        "elaborate",
        "deep analysis",
    ]
)

# =============================================================================
# CATEGORY / OPERATION KEYWORDS
# =============================================================================

CATEGORY_KEYWORDS: Dict[str, Tuple[str, ...]] = {
    "Performance": (
        "performance",
        "performances",
        "perform",
        "performing",
        "performed",
        "performer",
        "performers",
        "top performer",
        "top performers",
        "highest performer",
        "best performer",
        "bottom performer",
        "lowest performer",
        "grading",
        "grade",
        "grades",
        "graded",
        "grade distribution",
        "average score",
        "attempt",
        "attempts",
        "improvement",
        "improvements",
        "drop",
        "trend analysis",
    ),
    "Leave": (
        "leave",
        "leaves",
        "leaving",
        "left",
        "absent",
        "absentee",
        "absentees",
        "absence",
        "absconded",
        "absconding",
        "awol",
        "away",
        "missing",
        "untraceable",
        "unaccounted",
        "on leave",
        "days off",
        "off days",
        "leave taken",
        "never on leave",
        "leave status",
        "hospitalized",
        "sick",
    ),
    "Medical": (
        "medical",
        "medically",
        "medicine",
        "medicines",
        "health",
        "healthy",
        "bmi",
        "bmi distribution",
        "blood",
        "weight",
        "fitness",
        "fit",
        "disease",
        "diseases",
        "diagnosis",
        "diagnosed",
        "medical report",
        "medical issue",
        "medical issues",
        "health issue",
        "health issues",
        "admitted",
        "hospital",
        "sickness",
        "fever",
        "injury",
        "injured",
        "injuries",
        "obese",
        "obesity",
        "overweight",
        "underweight",
    ),
    "Attendance": (
        "attendance",
        "attendances",
        "attend",
        "attends",
        "attending",
        "attended",
        "attendee",
        "attendees",
        "present",
        "presence",
        "campus",
        "muster",
        "monthly",
        "weekly",
        "daily",
        "yearly",
    ),
    "Strength": (
        "strength",
        "strengths",
        "strength breakdown",
        "headcount",
        "headcounts",
        "headcount breakdown",
        "section",
        "current strength",
    ),
    "Verification": (
        "verification",
        "verifications",
        "verify",
        "verifying",
        "verified",
        "pending",
        "rejected",
        "rejection",
        "approved",
        "approval",
        "cleared",
    ),
    "Equipment": (
        "equipment",
        "equipments",
        "equip",
        "equipped",
        "equipping",
        "issued",
        "issuing",
        "holding",
        "returned",
        "returning",
        "search",
        "searching",
        "category",
        "item name",
        "find equipment",
        "lookup equipment",
        "condition",
        "gear",
        "kit",
        "inventory",
    ),
    "Distribution": (
        "distribution",
        "distributions",
        "distribute",
        "distributed",
        "distributing",
        "unit",
        "assigned",
        "assigning",
        "agniveer assignment",
        "unassigned",
        "assignment",
        "assignments",
        "pending assignment",
        "pending assignments",
    ),
    "Skills": (
        "skills",
        "skill",
        "skilled",
        "sport",
        "sports",
        "plays",
        "playing",
        "played",
        "player",
        "players",
        "good at",
        "talented in",
        "talent",
        "cricket",
        "football",
        "community",
        "roster",
        "rosters",
        "sport roster",
        "class roster",
        "sports roster",
        # Individual sport names are added programmatically at module load below
        # (see _SKILLS_SPORT_KEYWORDS extension at the bottom of this section)
    ),
    "Schedule": (
        "what's today's plan",
        "what's happening today",
        "show today's schedule",
        "what's the training today",
        "what's on for this company",
        "schedule for a specific person",
        "what's planned on this date",
        "schedule",
        "schedules",
        "scheduled",
        "scheduling",
        "training",
        "trainings",
        "agenda",
        "current schedule",
        "company schedule",
        "today's schedule",
        "today's training",
        "training schedule",
    ),
    "Overall": (
        "overall report",
        "how's he doing overall",
        "full picture",
        "everything combined",
        "total performance",
        "overall",
        "composite",
        "composite ranking",
        "all criteria",
    ),
    "personaldetail": (
        "tell me about him",
        "his details",
        "his info",
        "who is he",
        "his background",
        "his contact info",
        "his family info",
        "personal detail",
        "personal details",
        "personaldetail",
        "personal info",
        "personal",
        "profile",
        "profiles",
        "biography",
        "bio data",
        "biodata",
        "bio",
        "contact",
        "phone number",
        "email",
        "address",
        "education",
        "qualification",
        "qualifications",
        "family details",
        "next of kin",
        "kin details",
    ),
    "disqualified": (
        "who got kicked out",
        "who got removed",
        "who's out",
        "who got disqualified",
        "who left the program",
        "disqualified",
        "disqualify",
        "disqualifying",
        "disqualifies",
        "disqualification",
        "disqualified agniveer",
        "disqualified agniveers",
        "removed agniveer",
        "expelled",
        "expelled agniveer",
        "disqualification reason",
    ),
}

OPERATION_SYNONYMS: Dict[str, Dict[str, Tuple[str, ...]]] = {
    "Performance": {
        "Top": (
            "who is doing the best",
            "who is doing good",
            "who is doing great",
            "who's winning",
            "who's ahead",
            "who's the best one",
            "top guy",
            "top person",
            "best one",
            "best of all",
            "number 1",
            "no 1",
            "who scored the most",
            "who did the best",
            "who's leading",
            "who is doing the best",
            "who is doing good",
            "who is doing great",
            "who's winning",
            "who's ahead",
            "who's the best one",
            "top guy",
            "top person",
            "best one",
            "best of all",
            "number 1",
            "no 1",
            "who scored the most",
            "who did the best",
            "who's leading",
            "top",
            "highest",
            "higher",
            "best",
            "strongest",
            "greatest",
            "top performer",
            "top performers",
            "highest performer",
            "best scorer",
            "top scorer",
            "topper",
            "toppers",
            "topped",
            "who topped",
            "who scored highest",
            "leading performer",
            "outstanding performer",
            "ace performer",
            "stellar performer",
            "high achiever",
            "chart toppers",
            "number one performer",
            "leading scorer",
            "top scoring",
            "highest scoring",
            "cream of the crop",
            "leaders",
            "top ranked",
            "front runner",
            "highest achiever",
            "elite performer",
            "star performer",
            "highest marks",
            "best marks",
            "who is the best",
            "who is number one",
            "highest ranked agniveer",
        ),
        "Bottom": (
            "who is doing bad",
            "who is doing badly",
            "who is not doing good",
            "who's behind",
            "who's last",
            "worst one",
            "who did the worst",
            "who scored the least",
            "who's failing",
            "who needs help",
            "who's struggling",
            "weakest one",
            "who's not performing",
            "who is doing bad",
            "who is doing badly",
            "who is not doing good",
            "who's behind",
            "who's last",
            "worst one",
            "who did the worst",
            "who scored the least",
            "who's failing",
            "who needs help",
            "who's struggling",
            "weakest one",
            "who's not performing",
            "bottom",
            "lowest",
            "lower",
            "worst",
            "weakest",
            "poor",
            "failing",
            "bottom performer",
            "lowest performer",
            "worst performer",
            "poor performer",
            "weakest performer",
            "trailing performer",
            "struggling performer",
            "underperformer",
            "low scorer",
            "who scored lowest",
            "who performed worst",
            "least performing",
            "lagging behind",
            "bottom ranked",
            "poorest performer",
            "bottom scorer",
            "least scorer",
            "falling behind",
            "at the bottom",
            "sub par performer",
            "below average performer",
            "lowest marks",
            "worst marks",
            "who is the worst",
            "lowest ranked agniveer",
        ),
        "Improvement": (
            "who is getting better",
            "who improved",
            "who did better this time",
            "who's doing better now",
            "who came up",
            "whose score went up",
            "who's on the up",
            "getting good now",
            "improving fast",
            "who is getting better",
            "who improved",
            "who did better this time",
            "who's doing better now",
            "who came up",
            "whose score went up",
            "who's on the up",
            "getting good now",
            "improving fast",
            "improvement",
            "improve",
            "improved",
            "score went up",
            "scores went up",
            "went up",
            "positive trend",
            "biggest improvement",
            "most improved",
            "rising score",
            "upward trend",
            "who improved",
            "who got better",
            "score gain",
            "bounced back",
            "getting better",
            "progressing",
            "on the rise",
            "climbing up",
            "leveled up",
            "stepped up",
            "upward swing",
            "positive change",
            "gaining ground",
            "picking up pace",
            "growth in score",
            "moving up",
            "score increased",
            "showing improvement",
            "upward progress",
        ),
        "Drop": (
            "who got worse",
            "whose score went down",
            "who did badly this time",
            "who fell behind",
            "who's slipping",
            "who's not doing as good as before",
            "who dropped down",
            "who got worse",
            "whose score went down",
            "who did badly this time",
            "who fell behind",
            "who's slipping",
            "who's not doing as good as before",
            "who dropped down",
            "drop",
            "decline",
            "declined",
            "score drop",
            "downward trend",
            "negative trend",
            "who dropped",
            "who declined",
            "who got worse",
            "got worse",
            "fell",
            "slipped",
            "performance degraded",
            "regression",
            "regressed",
            "deterioration",
            "who is struggling more",
            "sliding down",
            "going down",
            "losing ground",
            "downward swing",
            "negative change",
            "score decrease",
            "worsening performance",
            "backsliding",
            "score fell",
            "score went down",
            "downward progress",
        ),
        "Grading": (
            "what grade did he get",
            "who got what grade",
            "show grades",
            "grade of each person",
            "who passed",
            "who failed",
            "pass or fail list",
            "what grade did he get",
            "who got what grade",
            "show grades",
            "grade of each person",
            "who passed",
            "who failed",
            "pass or fail list",
            "grading",
            "grade",
            "by grade",
            "grade wise",
            "who got excellent",
            "who got good",
            "who got sat",
            "categorised by grade",
            "categorized by grade",
            "grade wise breakdown",
            "grade classification",
            "sorted by grade",
            "grade bucket",
            "who is graded",
            "grade of",
            "which grade",
        ),
        "GradingSummary": (
            "how many passed",
            "how many failed",
            "how many got each grade",
            "grade count",
            "grade wise numbers",
            "how many passed",
            "how many failed",
            "how many got each grade",
            "grade count",
            "grade wise numbers",
            "grading summary",
            "grade summary",
            "distribution of grades",
            "how many in each grade",
            "grade count",
            "grade statistics",
            "grade tally",
            "grade count summary",
            "how many per grade",
            "grade totals",
            "overview of grades",
            "grade wise count",
            "grade breakdown summary",
        ),
        "Average": (
            "what's the average",
            "average score",
            "average marks",
            "normal score",
            "usual score",
            "what do people usually score",
            "what's the average",
            "average score",
            "average marks",
            "normal score",
            "usual score",
            "what do people usually score",
            "average",
            "avg",
            "mean",
            "average score",
            "average marks",
            "what is the average",
            "overall average",
            "mean score",
            "typical score",
            "on average",
            "score average",
            "average performance",
            "arithmetic mean",
            "average percentage",
            "average marks scored",
        ),
        "AttemptWise": (
            "show all tries",
            "show every attempt",
            "each try score",
            "attempt by attempt score",
            "all his attempts",
            "show all tries",
            "show every attempt",
            "each try score",
            "attempt by attempt score",
            "all his attempts",
            "attemptwise",
            "attempt wise",
            "by attempt",
            "attempt breakdown",
            "breakdown of attempts",
            "breakdown by attempt",
            "score per attempt",
            "each attempt",
            "all attempts",
            "multiple attempts",
            "attempt by attempt",
            "per attempt breakdown",
            "attempt level data",
            "attempt-wise data",
            "split by attempt",
            "attempt-wise scores",
            "scores by attempt",
        ),
        "BestAttempt": (
            "best try",
            "best score he got",
            "highest he ever scored",
            "his best one",
            "best try",
            "best score he got",
            "highest he ever scored",
            "his best one",
            "best attempt",
            "best score attempt",
            "highest attempt",
            "peak attempt",
            "personal best",
            "top attempt",
            "highest scoring attempt",
            "strongest attempt",
            "max attempt score",
            "record attempt",
            "best of all attempts",
        ),
        "Trend": (
            "how's he doing overall",
            "how's the group doing over time",
            "is it going up or down",
            "how's progress going",
            "how's he doing overall",
            "how's the group doing over time",
            "is it going up or down",
            "how's progress going",
            "trend",
            "trend analysis",
            "per attempt average",
            "attempt average",
            "average marks per attempt",
            "average percentage per attempt",
            "batch trend",
            "attempt trend",
            "performance trend",
            "score trend",
            "marks trend",
            "how is the batch performing",
            "how has the batch been performing",
            "performing over attempts",
            "performing over time",
            "batch performance over attempts",
            "performance over time",
            "score over time",
            "progress over attempts",
            "over attempts",
            "trajectory",
            "pattern over attempts",
            "how scores changed",
            "performance pattern",
            "score pattern over attempts",
        ),
    },
    "Leave": {
        "Most": (
            "who took the most leave",
            "who's off the most",
            "who takes the most days off",
            "who's absent the most",
            "who misses the most",
            "who took the most leave",
            "who's off the most",
            "who takes the most days off",
            "who's absent the most",
            "who misses the most",
            "most",
            "more",
            "highest",
            "larger",
            "largest",
            "maximum",
            "frequent",
            "most frequent",
            "most leave taken",
            "who has the most leave",
            "who took maximum leave",
            "most absent",
            "maximum absentee",
            "leave takers",
            "top leave takers",
            "most leaves",
            "maximum leaves",
            "highest leave count",
            "biggest leave taker",
            "leave champion",
            "took the most days off",
            "most days absent",
            "highest number of leaves",
        ),
        "Least": (
            "who takes the least leave",
            "who's hardly ever off",
            "who never misses",
            "who barely takes leave",
            "who's always there",
            "who takes the least leave",
            "who's hardly ever off",
            "who never misses",
            "who barely takes leave",
            "who's always there",
            "least",
            "less",
            "lowest",
            "smaller",
            "smallest",
            "minimum",
            "infrequent",
            "least frequent",
            "least leave taken",
            "who has the least leave",
            "fewest days absent",
            "fewest leaves",
            "most regular",
            "most punctual",
            "smallest leave count",
            "fewest days off",
            "least absent",
            "rarely absent",
            "hardly took leave",
            "hardly took any leave",
            "lowest number of leaves",
            # No dedicated "zero leave taken" operation exists — "never been
            # on leave" is functionally the extreme end of Least (fewest/no
            # days taken), so route it there instead of leaving it unhandled.
            "never been on leave",
            "never on leave",
            "never took leave",
            "never took a leave",
            "who never went on leave",
            "who has never been on leave",
            "no leave taken",
            "zero leave",
            "zero days off",
            "hasn't taken leave",
            "has not taken leave",
            "not taken any leave",
            "no days off taken",
        ),
        "Current": (
            "who's on leave right now",
            "who's off today",
            "who's not here today",
            "who's away today",
            "who's missing today",
            "who's on leave right now",
            "who's off today",
            "who's not here today",
            "who's away today",
            "who's missing today",
            "current",
            "today",
            "now",
            "currently on leave",
            "who is on leave",
            "leave status",
            "leave today",
            "absent today",
            "currently absent",
            "on leave right now",
            "currently away",
            "away today",
            "out today",
            "whos off today",
            "leave now",
            "who is away",
            "away right now",
            "who are away right now",
            "absent right now",
            "out right now",
            "missing today",
            "not present today",
            "who is absent today",
            "who's absent today",
        ),
        "Absconded": (
            "who ran away",
            "who's missing",
            "who disappeared",
            "who's not traceable",
            "who left without telling anyone",
            "who went missing",
            "who ran away",
            "who's missing",
            "who disappeared",
            "who's not traceable",
            "who left without telling anyone",
            "who went missing",
            "absconded",
            "abscond",
            "gone missing",
            "missing person",
            "awol",
            "whereabouts unknown",
            "unauthorized absence",
            "deserted",
            "ran away",
            "fled",
            "did not return",
            "overstayed leave",
            "went awol",
            "not traceable",
            "untraceable",
            "absent without leave",
            "gone awol",
            "unaccounted for",
            "cannot be located",
            "went missing",
        ),
    },
    "Medical": {
        "BMI": (
            "who's overweight",
            "who's underweight",
            "who's fit",
            "who's not fit",
            "weight status",
            "is he healthy weight wise",
            "who's overweight",
            "who's underweight",
            "who's fit",
            "who's not fit",
            "weight status",
            "is he healthy weight wise",
            "bmi",
            "weight",
            "fitness",
            "body mass index",
            "obese",
            "who is obese",
            "overweight",
            "underweight",
            "who is the fittest",
            "fittest",
            "most fit",
            "physically fit",
            "fit agniveer",
            "body weight status",
            "weight category",
            "bmi status",
            "bmi classification",
            "who is underweight",
            "who is overweight",
            "weight breakdown",
            "breakdown of weight",
            "breakdown by bmi",
            "obesity check",
        ),
        "BloodGroup": (
            "what's his blood group",
            "blood type list",
            "who has which blood group",
            "what's his blood group",
            "blood type list",
            "who has which blood group",
            "blood",
            "blood group",
            "blood type",
            "blood group distribution",
            "who has which blood group",
            "blood type distribution",
            "grouped by blood type",
            "blood group wise",
            "blood group breakdown",
            "blood type wise",
        ),
        "Disease": (
            "who's sick",
            "what's wrong with him",
            "what illness does he have",
            "who has a health problem",
            "common health issues",
            "who's sick",
            "what's wrong with him",
            "what illness does he have",
            "who has a health problem",
            "common health issues",
            "disease",
            "diseases",
            "diagnoses",
            "diagnosis",
            "top diseases",
            "common disease",
            "most common disease",
            "medical report",
            "illness",
            "ailment",
            "health condition",
            "medical condition",
            "sickness report",
            "common ailments",
            "who is sick with",
            "what illness",
            "disease breakdown",
            "breakdown of diseases",
            "breakdown by disease",
        ),
        "Individual": (
            "his medical report",
            "his health details",
            "check his medical record",
            "what's his health status",
            "his medical report",
            "his health details",
            "check his medical record",
            "what's his health status",
            "individual medical",
            "medical status of",
            "medical details of",
            "particular medical",
            "specific medical",
            "individual medical report",
            "medical report",
            "one person medical",
            "single agniveer medical",
            "medical record of",
            "medical records of",
            "health record of",
            "medical history of",
            "medical status for",
        ),
    },
    "Attendance": {
        "Monthly": (
            "attendance this month",
            "show me month wise attendance",
            "attendance this month",
            "show me month wise attendance",
            "monthly",
            "month",
            "monthly attendance",
            "attendance this month",
            "month wise",
            "attendance by month",
            "per month",
            "month by month",
            "monthly basis",
            "monthly report",
            "monthly breakdown",
        ),
        "Weekly": (
            "attendance this week",
            "attendance this week",
            "weekly",
            "week",
            "weekly attendance",
            "this week",
            "week wise",
            "attendance by week",
            "per week",
            "week by week",
            "weekly basis",
            "weekly report",
            "weekly breakdown",
        ),
        "Daily": (
            "attendance today",
            "how many days did he come",
            "show me day wise attendance",
            "attendance today",
            "how many days did he come",
            "show me day wise attendance",
            "daily",
            "day",
            "daily attendance",
            "day wise",
            "per day",
            "day by day",
            "daily basis",
            "daily report",
            "daily breakdown",
        ),
        "Present": (
            "who's here today",
            "who came today",
            "how many are here",
            "who showed up",
            "who's present",
            "who's here today",
            "who came today",
            "how many are here",
            "who showed up",
            "who's present",
            "present",
            "present today",
            "on campus",
            "who is present",
            "how many present",
            "attendance today",
            "today attendance",
            "in attendance",
            "checked in",
            "marked present",
            "showed up",
            "who came today",
            "who is here today",
        ),
        "Summary": (
            "overall attendance",
            "how's attendance looking",
            "general attendance report",
            "overall attendance",
            "how's attendance looking",
            "general attendance report",
            "attendance summary",
            "attendance overview",
            "summary of attendance",
            "overview of attendance",
            "overall attendance",
            "attendance recap",
            "attendance snapshot",
            "general attendance",
        ),
    },
    "Strength": {
        "StrengthBreakdown": (
            "how many people do we have",
            "total count",
            "how many in each section",
            "headcount",
            "how many people total",
            "how many people do we have",
            "total count",
            "how many in each section",
            "headcount",
            "how many people total",
            "strength",
            "strength breakdown",
            "breakdown of strength",
            "headcount",
            "headcount breakdown",
            "breakdown of headcount",
            "strength summary",
            "summary of strength",
            "current strength",
            "strength by section",
            "section strength",
            "manpower breakdown",
            "breakdown of manpower",
            "numbers by section",
            "unit strength",
            "personnel count",
            "count of personnel",
            "how many in each section",
            "how many agniveers are in each section",
            "manpower count",
            "count of manpower",
        ),
    },
    "Equipment": {
        "Stats": (
            "how much equipment do we have",
            "total equipment",
            "equipment count",
            "how much equipment do we have",
            "total equipment",
            "equipment count",
            "stats",
            "summary",
            "overview",
            "equipment stats",
            "equipment summary",
            "summary of equipment",
            "equipment inventory",
            "inventory stats",
            "equipment count",
            "count of equipment",
            "stock overview",
            "equipment numbers",
            "gear overview",
        ),
        "ByName": (
            "find this item",
            "look for this equipment",
            "do we have this",
            "where's this item",
            "find this item",
            "look for this equipment",
            "do we have this",
            "where's this item",
            "search",
            "byname",
            "search equipment",
            "find equipment",
            "lookup equipment",
            "equipment category",
            "item name",
            "by category",
            "by name",
            "look for equipment",
            "locate equipment",
            "find item",
            "equipment lookup",
            "check equipment",
        ),
        "Returned": (
            "who gave it back",
            "what came back damaged",
            "returned stuff",
            "broken stuff that came back",
            "who gave it back",
            "what came back damaged",
            "returned stuff",
            "broken stuff that came back",
            "returned",
            "return",
            "poor condition",
            "damaged",
            "bad condition",
            "broken",
            "sent back",
            "given back",
            "returned items",
            "handed back",
            "faulty returned",
            "faulty equipment",
            "defective items",
        ),
        "Holding": (
            "who has this item",
            "who's holding it",
            "who took this",
            "what does he have with him",
            "who has this item",
            "who's holding it",
            "who took this",
            "what does he have with him",
            "holding",
            "holds",
            "who is holding",
            "equipment holding",
            "currently issued",
            "currently holding",
            "issued",
            "issued items",
            "overdue",
            "in possession",
            "currently have",
            "still holding",
            "checked out items",
            "assigned equipment",
            "possessing",
            "who has issued items",
        ),
        "AgniveerWise": (
            "what does each person have",
            "show equipment per person",
            "who has what",
            "what does each person have",
            "show equipment per person",
            "who has what",
            "agniveer wise",
            "by agniveer",
            "agniveerwise",
            "byagniveer",
            "equipment by agniveer",
            "per agniveer equipment",
            "equipment per person",
            "individual equipment",
            "who has what equipment",
        ),
    },
    "Distribution": {
        "Latest": (
            "what was given out recently",
            "newest stuff given",
            "last batch given out",
            "what was given out recently",
            "newest stuff given",
            "last batch given out",
            "latest",
            "recent",
            "last",
            "newest",
            "most recent",
            "current",
            "fresh",
            "most recent distribution",
            "newly distributed",
            "just distributed",
            "recent allocation",
        ),
        "ByUnit": (
            "show by unit",
            "split by unit",
            "which unit got what",
            "show by unit",
            "split by unit",
            "which unit got what",
            "by unit",
            "unit wise",
            "in unit",
            "agniveers in unit",
            "unit distribution",
            "distribution of units",
            "distribution by unit",
            "per unit",
            "unit breakdown",
            "breakdown of units",
            "grouped by unit",
            "unit allocation",
        ),
        "Unassigned": (
            "what's not given to anyone yet",
            "leftover stuff",
            "stuff nobody has",
            "what's not given to anyone yet",
            "leftover stuff",
            "stuff nobody has",
            "unassigned",
            "not assigned",
            "not yet assigned",
            "yet to be assigned",
            "no unit",
            "without unit",
            "not allocated",
            "pending assignment",
            "no allocation",
        ),
        "TopUnit": (
            "which unit got the most",
            "which unit has the most people",
            "biggest unit",
            "which unit got the most",
            "which unit has the most people",
            "biggest unit",
            "top unit",
            "highest unit",
            "biggest unit",
            "largest unit",
            "maximum",
            "highest",
            "biggest",
            "largest",
            "unit with most",
            "biggest unit",
            "unit with the most agniveers",
            "received most agniveers",
            "most agniveers",
            "unit received most",
            "largest unit",
            "highest distribution",
            "most distribution",
            "unit with the highest count",
            "leading unit",
            "unit topping the list",
            "unit at the top",
        ),
    },
    "Skills": {
        "BySport": (
            "who plays what",
            "who plays cricket",
            "football players list",
            "sport wise list",
            "who plays what",
            "who plays cricket",
            "football players list",
            "sport wise list",
            "by sport",
            "sport wise",
            "cricket players",
            "football players",
            "who plays",
            "sports roster",
            "sport wise roster",
            "players by sport",
            "grouped by sport",
            "sport participation",
            "who is in sport",
        ),
        "ByClass": (
            "group wise list",
            "split by class",
            "who's in which group",
            "group wise list",
            "split by class",
            "who's in which group",
            "by class",
            "class wise",
            "class wise roster",
            "grouped by class",
            "class participation",
            "who is in class",
        ),
    },
    "Verification": {
        "Pending": (
            "still waiting",
            "not done yet",
            "still needs to be checked",
            "hasn't been verified yet",
            "still waiting",
            "not done yet",
            "still needs to be checked",
            "hasn't been verified yet",
            "pending",
            "awaiting",
            "not verified",
            "verification pending",
            "yet to be verified",
            "verification in progress",
            "still pending",
            "unverified",
            "waiting for verification",
        ),
        "Sent": (
            "already sent",
            "request already gone out",
            "already sent",
            "request already gone out",
            "sent",
            "sent verification",
            "verification sent",
            "verification requested",
            "request sent",
            "sent for verification",
            "dispatched for verification",
        ),
        "NotResponded": (
            "no reply yet",
            "they didn't answer",
            "still no response",
            "no reply yet",
            "they didn't answer",
            "still no response",
            "not responded",
            "no response",
            "awaiting response",
            "no reply",
            "did not respond",
            "unresponsive",
            "ignored request",
            "no acknowledgement",
        ),
        "Completed": (
            "all done",
            "finished checking",
            "verification done",
            "all done",
            "finished checking",
            "verification done",
            "completed",
            "done",
            "verification completed",
            "all clear",
            "verified",
            "all verified",
            "fully verified",
            "verification done",
            "closed out",
            "wrapped up",
            "finished verification",
        ),
        "Rejected": (
            "got rejected",
            "didn't get approved",
            "turned down",
            "got rejected",
            "didn't get approved",
            "turned down",
            "rejected",
            "not approved",
            "verification failed",
            "denied",
            "turned down",
            "declined",
            "disapproved",
            "verification denied",
        ),
    },
    "Schedule": {
        "bytoday": (
            "today",
            "today's schedule",
            "today schedule",
            "schedule today",
            "training schedule",
            "today's training",
            "current schedule",
            "today's agenda",
            "whats on today",
            "today's plan",
            "today's activities",
            "todays program",
            "bytoday",
        ),
        "bycompany": (
            "company schedule",
            "schedule by company",
            "company wise schedule",
            "schedule for company",
        ),
        "bydate": (
            "date wise schedule",
            "schedule on date",
            "schedule for date",
            "daily schedule",
            "bydate",
        ),
        "byagniveer": (
            "agniveer schedule",
            "schedule by agniveer",
            "agniveer wise schedule",
            "individual schedule",
            "personal schedule",
            "one agniveer's schedule",
            "schedule for agniveer",
        ),
    },
    "personaldetail": {
        "info": (
            "info",
            "information",
            "details",
            "personal details",
            "personal info",
            "profile",
            "biodata",
            "bio data",
            "contact",
            "education",
            "qualification",
            "family details",
            "next of kin",
            "kin details",
            "background of agniveer",
            "tell me about agniveer",
            "who is agniveer",
            "profile of agniveer",
            "personal record",
        ),
    },
    "disqualified": {
        "removed": (
            "removed",
            "disqualified",
            "disqualification",
            "disqualified agniveer",
            "disqualified agniveers",
            "removed agniveer",
            "expelled agniveer",
            "disqualification reason",
            "kicked out",
            "washed out",
            "terminated",
            "let go",
            "released from service",
            "de-enrolled",
            "discharged",
        ),
    },
    "Overall": {
        "OverallPerformance": (
            "overall performance",
            "overall report",
            "composite report",
            "composite ranking",
            "all criteria",
            "all criteria performance",
            "holistic performance",
            "overall standing",
            "cumulative performance",
            "total performance",
            "across the board performance",
        ),
    },
}

# =============================================================================
# SECTIONS (PERFORMANCE DOMAIN ONLY)
# =============================================================================

SECTION: Dict[str, Dict[str, Any]] = {
    "BPET": {
        "name": "BPET",
        "aliases": ("bpet", "betp", "bept"),
        "isExceptional": False,
    },
    "PPT": {
        "name": "PPT",
        "aliases": ("ppt", "pptt"),
        "isExceptional": False,
    },
    "Firing": {
        "name": "Firing",
        "aliases": ("firing", "fiiring", "firng", "fring", "fireing"),
        "isExceptional": False,
    },
    "Drill": {
        "name": "Drill",
        "aliases": ("drill", "drll", "dril"),
        "isExceptional": False,
    },
    "Map Reading": {
        "name": "Map Reading",
        "aliases": ("map reading", "mapreading"),
        "isExceptional": True,
    },
    "Tactics": {
        "name": "Tactics",
        "aliases": ("tactics",),
        "isExceptional": True,
    },
    "Exceptional Sport": {
        "name": "Exceptional Sport",
        "aliases": ("exceptional sport", "exceptionalSport", "exceptional_sport"),
        "isExceptional": True,
    },
    "BFC": {
        "name": "BFC",
        "aliases": ("bfc",),
        "isExceptional": True,
    },
    "PDP": {
        "name": "PDP",
        "aliases": ("pdp",),
        "isExceptional": True,
    },
    "MR": {
        "name": "MR",
        "aliases": ("mr",),
        "isExceptional": True,
    },
    "IT": {
        "name": "IT",
        "aliases": ("it",),
        "isExceptional": True,
    },
    "FC/BC": {
        "name": "FC/BC",
        "aliases": ("fc/bc", "fcbc", "fc bc"),
        "isExceptional": True,
    },
    "CBRN": {
        "name": "CBRN",
        "aliases": ("cbrn",),
        "isExceptional": True,
    },
    "Test Written (AMT)": {
        "name": "Test Written (AMT)",
        "aliases": ("test written", "test written amt"),
        "isExceptional": True,
    },
    "Test Prac (AMT)": {
        "name": "Test Prac (AMT)",
        "aliases": ("test prac", "test prac amt"),
        "isExceptional": True,
    },
}

# =============================================================================
# SUBSECTIONS (BY SECTION)
# =============================================================================

SUBSECTIONS_BY_SECTION: Dict[str, List[str]] = {
    "BPET": ["5km", "60m Sprint", "9' Ditch", "H Rope", "V Rope"],
    "PPT": ["2.4km", "100m Sprint", "Chin Ups", "Sit Ups", "Toe Touch", "5m Shuttle"],
    "Firing": [
        "300m 5 FTS",
        "200m 5 FTS",
        "100m LU (R)",
        "100m LU (5/5)",
        "50m SU TRU",
        "100m NI SFTS SS",
        "15m (Bal) BC",
    ],
    "Drill": [
        "Turn Out and Bearing",
        "Word of Command",
        "Marching",
        "Slow March",
        "Saluting Salami Shastra",
        "Turning",
    ],
}

# Common phrasing variants for subsections that don't literally match the
# stored name's punctuation/spacing/units — matched in ADDITION to the
# canonical name itself (`_extract_subsection` checks both). Kept sparse for
# the Firing codes (abbreviated military jargon) rather than guessing at
# expansions we can't verify.
SUBSECTION_ALIASES: Dict[str, Tuple[str, ...]] = {
    "5km": ("5 km", "5-km", "5 kilometer", "5 kilometre", "5000m", "5000 m"),
    "60m Sprint": ("60m sprint", "60 m sprint", "60 meter sprint", "60 metre sprint", "60m dash"),
    "9' Ditch": ("9 ditch", "9-foot ditch", "9 foot ditch", "9ft ditch", "nine foot ditch"),
    "H Rope": ("h rope", "horizontal rope", "h-rope"),
    "V Rope": ("v rope", "vertical rope", "v-rope"),
    "2.4km": ("2.4 km", "2.4-km", "2400m", "2400 m", "2.4 kilometer", "2.4 kilometre"),
    "100m Sprint": ("100m sprint", "100 m sprint", "100 meter sprint", "100 metre sprint"),
    "Chin Ups": ("chin ups", "chinups", "chin-ups", "chin up"),
    "Sit Ups": ("sit ups", "situps", "sit-ups", "sit up"),
    "Toe Touch": ("toe touch", "toe-touch", "toetouch", "toe touches"),
    "5m Shuttle": ("5m shuttle", "5 m shuttle", "5 meter shuttle", "5 metre shuttle", "shuttle run"),
    "Turn Out and Bearing": ("turnout and bearing", "turn out bearing", "turnout bearing"),
    "Word of Command": ("words of command", "command words", "word of commands"),
    "Slow March": ("slow marching",),
    "Saluting Salami Shastra": ("saluting",),
}

# =============================================================================
# GRADING CATEGORIES
# =============================================================================

GRADING_CATEGORIES: Dict[str, str] = {
    "exceptionally well": "ExceptionallyWell",
    "excellent": "Excellent",
    "good": "Good",
    "sat": "SAT",
    "satisfactory": "SAT",
    "fail": "Fail",
    "failed": "Fail",
    "failing": "Fail",
}

# =============================================================================
# LEAVE TYPES
# =============================================================================

LEAVE_TYPES: Dict[str, str] = {
    "annual": "Annual",
    "medical": "Medical",
    "sick": "Sick",
    "absconded": "Absconded",
    "attnc": "ATTNC",
    "attenc": "ATTNC",
    "attn c": "ATTNC",
    "att nc": "ATTNC",
    "ex ppg": "ExPPG",
    "exppg": "ExPPG",
    "ex-ppg": "ExPPG",
    "hospitalized": "Hospitalized",
    "threshold": "Threshold",
    "90%": "Threshold",
    "90 %": "Threshold",
    "90% leave used": "Threshold",
    "above threshold": "Threshold",
    "near leave limit": "Threshold",
    "almost exhausted": "Threshold",
    "high leave usage": "Threshold",
    "leave threshold": "Threshold",
    "leave utilization": "Threshold",
    "leave risk": "Threshold",
    "critical leave": "Threshold",
    "noleave": "NoLeave",
}

# =============================================================================
# BMI CATEGORIES
# =============================================================================

BMI_CATEGORIES: Dict[str, str] = {
    "underweight": "Underweight",
    "normal": "Normal",
    "overweight": "Overweight",
    "obese": "Obese",
    # "fit" family kept here for context-guarded lookup in entity_extractor.py;
    # they only activate when the query also contains "bmi", "weight", or "fitness".
    "fittest": "Normal",
    "fit": "Normal",
    "most fit": "Normal",
    "physically fit": "Normal",
}

# =============================================================================
# BLOOD GROUPS
# =============================================================================

BLOOD_GROUPS: FrozenSet[str] = frozenset(
    [
        "A+",
        "A-",
        "B+",
        "B-",
        "O+",
        "O-",
        "AB+",
        "AB-",
    ]
)

# =============================================================================
# SPORTS
# =============================================================================

SPORTS: Dict[str, str] = {
    "cricket": "Cricket",
    "football": "Football",
    "soccer": "Football",
    "running": "Running",
    "athletics": "Athletics",
    "basketball": "Basketball",
    "volleyball": "Volleyball",
    "kabaddi": "Kabaddi",
    "hockey": "Hockey",
    "badminton": "Badminton",
    "tennis": "Tennis",
    "lawn tennis": "Tennis",
    "table tennis": "Table Tennis",
    "ping pong": "Table Tennis",
    "swimming": "Swimming",
    "wrestling": "Wrestling",
    "kushti": "Wrestling",
    "boxing": "Boxing",
    "archery": "Archery",
    "shooting": "Shooting",
    "weightlifting": "Weightlifting",
    "gymnastics": "Gymnastics",
    "cycling": "Cycling",
    "chess": "Chess",
    "carrom": "Carrom",
    "kho kho": "Kho Kho",
    "kho-kho": "Kho Kho",
    "squash": "Squash",
    "billiards": "Billiards",
    "snooker": "Snooker",
    "pool": "Pool",
    "judo": "Judo",
    "karate": "Karate",
    "taekwondo": "Taekwondo",
    "martial arts": "Martial Arts",
    "handball": "Handball",
    "rugby": "Rugby",
    "golf": "Golf",
    "rowing": "Rowing",
    "sailing": "Sailing",
    "fencing": "Fencing",
    "equestrian": "Equestrian",
    "horse riding": "Equestrian",
    "polo": "Polo",
    "cross country": "Cross Country",
    "marathon": "Marathon",
}

# Extend CATEGORY_KEYWORDS["Skills"] with all sport names from SPORTS so that
# any sport keyword automatically scores against the Skills category.
def _extend_skills_keywords() -> None:
    base: Tuple[str, ...] = CATEGORY_KEYWORDS.get("Skills", ())
    sport_additions = tuple(
        k for k in SPORTS if k not in base
    ) + tuple(
        v.lower() for v in SPORTS.values() if v.lower() not in base
    )
    CATEGORY_KEYWORDS["Skills"] = tuple(dict.fromkeys(base + sport_additions))


_extend_skills_keywords()

# =============================================================================
# CLASSES
# =============================================================================

CLASSES: Dict[str, str] = {
    "sikh": "Sikh",
    "oic": "OIC",
    "gurkha": "Gurkha",
    "gorkha": "Gurkha",
    "dogra": "Dogra",
    "jat": "Jat",
    "rajput": "Rajput",
    "punjabi": "Punjabi",
}

# =============================================================================
# EQUIPMENT ITEMS
# =============================================================================

ISSUED_EQUIPMENT_ITEMS: List[str] = [
    "Pt Shoes Brown",
    "Cap FS",
    "Mug Steel",
    "Blanket",
    "DMS Boot GP",
    "Terry Towel Light Blue",
    "Under Pant Woollen",
    "Vest Woollen OG FS",
    "Vest Cotton H/S RN",
    "Pt Dress",
    "Ground Shed",
    "Kit Bag",
    "Combat T Shirt",
    "Net Mosquito",
    "Pagari 5.5m",
    "Combat Coat",
    "Belt ICK",
    "Combat Dress",
    "Line Bedding",
    "FFD",
    "Cover Water Proof OG",
    "Cover Water Pro Sikh",
    "Haver Shack All Rank",
    "Boot High Ankle DVS",
    "Spoon Desert",
    "Frog Bayonet ICK",
    "Net Camouflage H/D",
    "Lases Nylon Black 100cm for Footwear",
    "Pouches Amn ICK",
    "Pack with Allmn Frame",
    "Cord Disk identity",
    "Disk identity Oval",
    "Disk identity Round",
    "Water Bottle Plastic with C",
    "Vest Cotton White S4",
    "Drawers Cotton White",
    "Jersey V Neck",
    "Short KD",
    "Knee & Elbow",
    "Socks Woollen OG",
    "Trouser Drill Khaki Poly",
    "Shirt Man Khaki Poly",
    "Short KD Light Green",
    "Jersey Man Woollen OG",
    "Shirt Angola Drive",
    "Trouser Bd Serge",
]

PROCURED_EQUIPMENT_ITEMS: List[str] = [
    "Rect Bag (Khaki)",
    "Pt Shoes",
    "Mufti Shoes",
    "Black Socks",
    "Black Pagri with Fifty",
    "Drill Shoes",
    "PT Dress Complete",
    "Games Dress",
    "Mufti Dress (White)",
    "Regt Tie with Clip",
    "Mufti Dress (Winter) / Mufti Blazer",
    "Khaki Half Sleeves (Drill)",
    "Khaki Full Sleeves (WT & Drill)",
    "Socks OG",
    "Green Pagri with Fifty",
    "OG Dress",
    "Combat Cap",
    "Leather Belt with Crest",
    "Bed Sheet",
    "Rect Shoulder",
    "Name Plate (Black)",
    "Name Plate (Khaki)",
    "Belt (Black)",
    "Water Bottle 02 Ltr",
    "Mug Plastic",
    "Box Steel with Paint",
    "Hanger",
    "Health Card",
    "Bed Card",
    "Locker Cloth",
    "Firing Data Card",
    "Vest",
    "Track Suit with Name",
    "Clip Board",
    "256 Pages Copy",
    "White Hanky",
    "Steel Thali",
    "Glass (Steel)",
    "Spoon (Steel)",
    "Soap Case",
    "Indls Photograph",
    "Small Bucket",
    "Progress Card",
    "Mattress",
    "Angola Shirt with OG Pant",
    "Big Bucket",
    "PT Vest with Chest No",
    "Underwear",
    "Swimming Costumes",
    "Swimming Cover",
    "Jungle Shoes",
    "Barret Cap",
    "Rifle Sling",
]

# =============================================================================
# VERIFICATION STATUSES
# =============================================================================

VERIFICATION_STATUSES: Dict[str, str] = {
    "pending": "Pending",
    "sent": "Sent",
    "not responded": "NotResponded",
    "verified": "Verified",
    "rejected": "Rejected",
}

# =============================================================================
# CATEGORY-ENTITY COMPATIBILITY
# =============================================================================

# Which entity types are ALLOWED for each category
CATEGORY_ENTITY_COMPATIBILITY: Dict[str, Set[str]] = {
    "Performance": {
        "section",
        "subSection",
        "grading",
        "attemptNo",
        "fromAttempt",
        "toAttempt",
        "sport",
        "class",
    },
    "Leave": {"leaveType", "sport", "class"},
    "Medical": {
        "bmiCategory",
        "bloodGroup",
        "medicalStatus",
        "sport",
        "class",
        "diagnose",
    },
    "Attendance": {"date", "fromDate", "toDate", "sport", "class"},
    "Verification": {"sport", "class"},
    "Strength": {"section"},
    "Equipment": {"equipmentName", "equipmentType", "itemName", "itemCategory", "sport", "class"},
    "Distribution": {"sport", "class"},
    "Skills": {"sport", "class", "section", "subSection"},
    "Overall": {"sport", "class"},
    "Schedule": {"date", "sport", "class"},
    "personaldetail": {"sport", "class"},
    "disqualified": {"sport", "class"},
}

# Common entities allowed in ALL categories
COMMON_ENTITY_TYPES: Set[str] = {
    "companyId",
    "platoonId",
    "batchId",
    "agniveerNo",
    "unitName",
    "n",
    "date",
    "fromDate",
    "toDate",
    "days",
    "givenCondition",
    "returnCondition",
}

CATEGORY_ENTITY_HINTS: Dict[str, Tuple[str, ...]] = {
    "Performance": (
        "section", "grading", "attempt", "score", "marks", "trend",
        "performance", "performer", "performers", "grade", "grades",
        "improvement", "improved", "drop", "dropped", "decline", "declined",
        "average", "percentage", "ranking", "ranked", "attemptwise",
        "best attempt", "grading summary", "grade summary",
    ),
    "Leave": (
        "leave", "absent", "abscond", "leaveType", "leaves", "absentee",
        "absconded", "awol", "annual leave", "sick leave", "medical leave",
        "on leave", "absent today", "day off", "days off", "leave status",
        "leave taken", "who is away", "sick", "hospitalized",
    ),
    "Medical": (
        "medical", "hospital", "bmi", "blood", "obese", "overweight", "underweight", "Normal",
        "disease", "diseases", "diagnosis", "illness", "ailment", 
        "fever", "injury", "injured", "fracture", "wound", "dengue",
        "malaria", "typhoid", "blood group", "blood type", "fitness",
        "patient", "ward", "medical record", "health status",
    ),
    "Attendance": (
        "attendance", "present", "campus", "date", "monthly attendance",
        "weekly attendance", "daily attendance", "present today",
        "attendance summary", "attendance overview", "muster",
        "checked in", "marked present", "who came today",
    ),
    "Strength": (
        "strength", "breakdown", "headcount", "manpower", "personnel count",
        "current strength", "unit strength", "strength summary",
        "headcount breakdown", "how many in each section",
    ),
    "Verification": (
        "verification", "verified", "pending", "rejected", "unverified",
        "not responded", "completed verification", "sent verification",
        "awaiting verification", "disapproved", "denied", "verification status",
        "all clear",
    ),
    "Equipment": (
        "equipment", "gear", "inventory", "search", "category", "name",
        "issued", "holding", "overdue", "returned", "damaged", "kit",
        "stock", "possession", "checked out", "handed back",
        "equipment stats", "equipment summary",
    ),
    "Distribution": (
        "distribution", "unit", "unassigned", "allocation", "allocated",
        "assignment", "assignments", "distributed", "top unit", "by unit",
        "unit wise", "pending assignment", "grouped by unit",
    ),
    "Skills": (
        "skills", "sport", "roster", "who plays", "player", "players",
        "plays", "sport roster", "sport wise", "by sport", "talented in",
        "good at", "sports roster", "class roster", "class wise roster",
    ),
    "Overall": (
        "overall", "composite", "all criteria", "composite ranking",
        "holistic", "cumulative", "standing", "overall standing",
        "overall report", "overall ranking",
    ),
    "Schedule": (
        "schedule", "training", "bycompany", "byagniveer", "bydate", "bytoday",
        "agenda", "training plan", "today's schedule", "timetable",
        "training schedule", "today's agenda", "today's plan",
    ),
    "personaldetail": (
        "profile",
        "contact",
        "address",
        "education",
        "family",
        "details",
        "personal detail",
        "biodata",
        "bio data",
        "qualification",
        "next of kin",
        "personal info",
        "background",
        "who is agniveer",
        "tell me about",
    ),
    "disqualified": (
        "disqualified", "removed", "expelled", "washed out", "terminated",
        "discharged", "kicked out", "de-enrolled", "released from service",
    ),
}

# Named unit aliases that should normalize to canonical unit labels.
UNIT_ALIASES: Dict[str, str] = {
    "alpha": "Alpha Unit",
    "bravo": "Bravo Unit",
    "charlie": "Charlie Unit",
    "delta": "Delta Unit",
    "echo": "Echo Unit",
    "foxtrot": "Foxtrot Unit",
    "golf": "Golf Unit",
    "hotel": "Hotel Unit",
    "india": "India Unit",
    "juliet": "Juliet Unit",
    "kilo": "Kilo Unit",
    "lima": "Lima Unit",
    "mike": "Mike Unit",
    "november": "November Unit",
    "oscar": "Oscar Unit",
    "papa": "Papa Unit",
    "quebec": "Quebec Unit",
    "romeo": "Romeo Unit",
    "sierra": "Sierra Unit",
    "tango": "Tango Unit",
    "uniform": "Uniform Unit",
    "victor": "Victor Unit",
    "whiskey": "Whiskey Unit",
    "xray": "Xray Unit",
    "yankee": "Yankee Unit",
    "zulu": "Zulu Unit",
}

# Relative date phrases returned by the extractor in canonical form.
RELATIVE_DATE_PHRASES: Dict[str, str] = {
    "today": "today",
    "yesterday": "yesterday",
    "tomorrow": "tomorrow",
    "this week": "this week",
    "last week": "last week",
    "this month": "current month",
    "current month": "current month",
    "last month": "last month",
    "this year": "this year",
    "current year": "this year",
}

# Ranking cue words used to distinguish counts from IDs.
RANKING_CONTEXT_PHRASES: Tuple[str, ...] = (
    "top",
    "bottom",
    "highest",
    "lowest",
    "best",
    "worst",
    "rank",
    "topped",
    "scored highest",
    "performed worst",
    "most",
    "least",
)

NEGATIVE_REPORT_PHRASES: List[str] = [
    "no matching data",
    "empty dataset",
    "no records available",
    "zero active",
    "no future trend projection",
    "insufficient data",
    "could not be completed",
    "returned zero",
    "returned 0 records",
]


# =============================================================================
# FUZZY VOCABULARY (MISSPELLINGS)
# =============================================================================

FUZZY_VOCAB: Dict[str, str] = {
    "perfomance": "Performance",
    "performace": "Performance",
    "performence": "Performance",
    "prefomance": "Performance",
    "preformance": "Performance",
    "performnce": "Performance",
    "perfromance": "Performance",
    "leve": "Leave",
    "leeve": "Leave",
    "laeve": "Leave",
    "leav": "Leave",
    "medcal": "Medical",
    "meical": "Medical",
    "medicl": "Medical",
    "medicel": "Medical",
    "attendence": "Attendance",
    "attendnce": "Attendance",
    "atendance": "Attendance",
    "attandance": "Attendance",
    "attendnace": "Attendance",
    "strenght": "Strength",
    "strengh": "Strength",
    "strenth": "Strength",
    "verfication": "Verification",
    "verifcation": "Verification",
    "verificaton": "Verification",
    "varification": "Verification",
    "verifcaton": "Verification",
    "equipement": "Equipment",
    "equiptment": "Equipment",
    "equipmnt": "Equipment",
    "equpment": "Equipment",
    "equimpent": "Equipment",
    "distribtion": "Distribution",
    "distributon": "Distribution",
    "distibution": "Distribution",
    "distrubution": "Distribution",
    "skils": "Skills",
    "skiils": "Skills",
    "sklls": "Skills",
    "overal": "Overall",
    "ovreall": "Overall",
    "overrall": "Overall",
    "schedul": "Schedule",
    "schedual": "Schedule",
    "shedule": "Schedule",
    "sechdule": "Schedule",
    "personaldetal": "personaldetail",
    "personldetail": "personaldetail",
    "persnal detail": "personaldetail",
    "personel detail": "personaldetail",
    "disqualifed": "disqualified",
    "disqualifyed": "disqualified",
    "disqalified": "disqualified",
    "dequalified": "disqualified",
    "tpo": "Top",
    "top": "Top",
    "tp": "Top",
    "topp": "Top",
    "botom": "Bottom",
    "bottm": "Bottom",
    "botton": "Bottom",
    "bottem": "Bottom",
    "improvment": "Improvement",
    "improvemnt": "Improvement",
    "improov": "Improvement",
    "imporvement": "Improvement",
    "dorp": "Drop",
    "drpo": "Drop",
    "dropp": "Drop",
    "gradig": "Grading",
    "gradng": "Grading",
    "gradeing": "Grading",
    "graading": "Grading",
    "gradingsumary": "GradingSummary",
    "gradesummry": "GradingSummary",
    "gradingsummery": "GradingSummary",
    "avrage": "Average",
    "averge": "Average",
    "avrg": "Average",
    "avreage": "Average",
    "atemptwise": "AttemptWise",
    "attemtwise": "AttemptWise",
    "attemptwize": "AttemptWise",
    "bestattemp": "BestAttempt",
    "bestatempt": "BestAttempt",
    "bstattempt": "BestAttempt",
    "trned": "Trend",
    "trand": "Trend",
    "mst": "Most",
    "moust": "Most",
    "mosst": "Most",
    "lest": "Least",
    "leats": "Least",
    "curent": "Current",
    "curr": "Current",
    "currnt": "Current",
    "abscnded": "Absconded",
    "absconed": "Absconded",
    "abscondd": "Absconded",
    "abscound": "Absconded",
    "threshhold": "Threshold",
    "threshold": "Threshold",
    "thresold": "Threshold",
    "bmii": "BMI",
    "mbi": "BMI",
    "blodgroup": "BloodGroup",
    "bloodgrup": "BloodGroup",
    "blod group": "BloodGroup",
    "bloood group": "BloodGroup",
    "disese": "Disease",
    "diseae": "Disease",
    "dises": "Disease",
    "deseas": "Disease",
    "deseasse": "Disease",
    "dizease": "Disease",
    "diseaze": "Disease",
    "disiese": "Disease",
    "indvidual": "Individual",
    "individul": "Individual",
    "indivdual": "Individual",
    "montly": "Monthly",
    "monthyl": "Monthly",
    "monthy": "Monthly",
    "weekli": "Weekly",
    "weekley": "Weekly",
    "weekyl": "Weekly",
    "daili": "Daily",
    "dialy": "Daily",
    "dayly": "Daily",
    "presnt": "Present",
    "preent": "Present",
    "presant": "Present",
    "sumary": "Summary",
    "summry": "Summary",
    "sumarry": "Summary",
    "strenghtbreakdown": "StrengthBreakdown",
    "strengthbrakdown": "StrengthBreakdown",
    "strenghbreakdown": "StrengthBreakdown",
    "pendng": "Pending",
    "pendign": "Pending",
    "pendding": "Pending",
    "snet": "Sent",
    "sentt": "Sent",
    "cent": "Sent",
    "notresponded": "NotResponded",
    "notrespondd": "NotResponded",
    "no responsed": "NotResponded",
    "complted": "Completed",
    "compleated": "Completed",
    "rejcted": "Rejected",
    "rejeted": "Rejected",
    "regected": "Rejected",
    "stat": "Stats",
    "stast": "Stats",
    "staats": "Stats",
    "serch": "Search",
    "saerch": "Search",
    "sarch": "Search",
    "returnd": "Returned",
    "retuned": "Returned",
    "retruned": "Returned",
    "holdng": "Holding",
    "holidng": "Holding",
    "hodling": "Holding",
    "agniverwise": "AgniveerWise",
    "agniveerwize": "AgniveerWise",
    "agniveerwis": "AgniveerWise",
    "latst": "Latest",
    "lattest": "Latest",
    "laetst": "Latest",
    "byunit": "ByUnit",
    "by unti": "ByUnit",
    "byunti": "ByUnit",
    "unasigned": "Unassigned",
    "unassignd": "Unassigned",
    "unassgined": "Unassigned",
    "topunt": "TopUnit",
    "topunit": "TopUnit",
    "tpounit": "TopUnit",
    "bysprot": "BySport",
    "bysport": "BySport",
    "by sprot": "BySport",
    "byclas": "ByClass",
    "byclass": "ByClass",
    "by clss": "ByClass",
    "bytoady": "bytoday",
    "bytody": "bytoday",
    "by todya": "bytoday",
    "bycompny": "bycompany",
    "by compnay": "bycompany",
    "bycompani": "bycompany",
    "bydat": "bydate",
    "by daet": "bydate",
    "byagniver": "byagniveer",
    "byagniveer": "byagniveer",
    "by agniver": "byagniveer",
    "inffo": "info",
    "infoo": "info",
    "infomation": "info",
    "remvoed": "removed",
    "removd": "removed",
    "remoevd": "removed",
    "overallperfomance": "OverallPerformance",
    "overallperfromance": "OverallPerformance",
    "overal performance": "OverallPerformance",
    "bpett": "BPET",
    "bpaet": "BPET",
    "bpeet": "BPET",
    "pptt": "PPT",
    "pptte": "PPT",
    "ppte": "PPT",
    "firrng": "Firing",
    "fiirng": "Firing",
    "fyring": "Firing",
    "dryll": "Drill",
    "dryl": "Drill",
    "drilll": "Drill",
    "map redaing": "Map Reading",
    "mapreadng": "Map Reading",
    "map reeding": "Map Reading",
    "tatics": "Tactics",
    "tactcs": "Tactics",
    "tactis": "Tactics",
    "bfcc": "BFC",
    "bffc": "BFC",
    "pddp": "PDP",
    "pdpp": "PDP",
    "cbrnn": "CBRN",
    "cbnr": "CBRN",
    "exceptionaly well": "ExceptionallyWell",
    "exceptionly well": "ExceptionallyWell",
    "excepionally well": "ExceptionallyWell",
    "excelent": "Excellent",
    "excellnt": "Excellent",
    "exellent": "Excellent",
    "goood": "Good",
    "goo": "Good",
    "gud": "Good",
    "statisfactory": "Satisfactory",
    "satisfactroy": "Satisfactory",
    "satisfactary": "Satisfactory",
    "fial": "Fail",
    "faill": "Fail",
    "fael": "Fail",
    "anual": "Annual",
    "annuall": "Annual",
    "anaul": "Annual",
    "sik": "Sick",
    "sic": "Sick",
    "sikc": "Sick",
    "hospitalzed": "Hospitalized",
    "hospitlized": "Hospitalized",
    "hospitalizd": "Hospitalized",
    "atnc": "ATTNC",
    "atc": "ATTNC",
    "attnce": "ATTNC",
    "exppg": "ExPPG",
    "ex-pgg": "ExPPG",
    "expg": "ExPPG",
    "noleav": "NoLeave",
    "no leav": "NoLeave",
    "noleve": "NoLeave",
    "underwieght": "Underweight",
    "undreweight": "Underweight",
    "underweigt": "Underweight",
    "norml": "Normal",
    "noraml": "Normal",
    "normall": "Normal",
    "overwieght": "Overweight",
    "overweigt": "Overweight",
    "ovrweight": "Overweight",
    "obesse": "Obese",
    "obease": "Obese",
    "obes": "Obese",
    "verfied": "Verified",
    "verifed": "Verified",
    "verfyed": "Verified",
    "sihk": "Sikh",
    "sihkh": "Sikh",
    "sikkh": "Sikh",
    "gurkah": "Gurkha",
    "ghurka": "Gurkha",
    "gorka": "Gurkha",
    "dogar": "Dogra",
    "dogera": "Dogra",
    "jaat": "Jat",
    "jatt": "Jat",
    "rajpoot": "Rajput",
    "rajputt": "Rajput",
    "punjabee": "Punjabi",
    "panjabi": "Punjabi",
    "punjabbi": "Punjabi",
    "criket": "Cricket",
    "crciket": "Cricket",
    "crikcet": "Cricket",
    "footbal": "Football",
    "footbol": "Football",
    "fotball": "Football",
    "voleyball": "Volleyball",
    "vollyball": "Volleyball",
    "volyball": "Volleyball",
    "basketbal": "Basketball",
    "baskteball": "Basketball",
    "baskeball": "Basketball",
    "hocky": "Hockey",
    "hokey": "Hockey",
    "hoky": "Hockey",
    "badmintion": "Badminton",
    "badminten": "Badminton",
    "badmiton": "Badminton",
    "tenis": "Tennis",
    "tennnis": "Tennis",
    "swiming": "Swimming",
    "swiimming": "Swimming",
    "wrestlng": "Wrestling",
    "resling": "Wrestling",
    "wresling": "Wrestling",
    "boxng": "Boxing",
    "boxxing": "Boxing",
    "kabadi": "Kabaddi",
    "kabbadi": "Kabaddi",
    "kabaadi": "Kabaddi",
    "chess": "Chess",
    "ches": "Chess",
    "carom": "Carrom",
    "carrum": "Carrom",
    "alfa": "Alpha Unit",
    "alpah": "Alpha Unit",
    "brayvo": "Bravo Unit",
    "bravoo": "Bravo Unit",
    "charlei": "Charlie Unit",
    "charle": "Charlie Unit",
    "delt": "Delta Unit",
    "deltaa": "Delta Unit",
    "ecoh": "Echo Unit",
    "echoo": "Echo Unit",
    "foxtrott": "Foxtrot Unit",
    "foxtort": "Foxtrot Unit",
    "hotell": "Hotel Unit",
    "hotel": "Hotel Unit",
    "indya": "India Unit",
    "indiaa": "India Unit",
    "julliet": "Juliet Unit",
    "juliett": "Juliet Unit",
    "killo": "Kilo Unit",
    "kilio": "Kilo Unit",
    "lma": "Lima Unit",
    "leema": "Lima Unit",
    "miek": "Mike Unit",
    "mikee": "Mike Unit",
    "novmber": "November Unit",
    "novembr": "November Unit",
    "oskar": "Oscar Unit",
    "oscarr": "Oscar Unit",
    "pappa": "Papa Unit",
    "papaa": "Papa Unit",
    "quebeck": "Quebec Unit",
    "kebec": "Quebec Unit",
    "romio": "Romeo Unit",
    "romeoo": "Romeo Unit",
    "sierraa": "Sierra Unit",
    "siera": "Sierra Unit",
    "tanggo": "Tango Unit",
    "tangoo": "Tango Unit",
    "unifrom": "Uniform Unit",
    "uniforme": "Uniform Unit",
    "victr": "Victor Unit",
    "viktor": "Victor Unit",
    "whisky": "Whiskey Unit",
    "wiskey": "Whiskey Unit",
    "xrayy": "Xray Unit",
    "x-ray": "Xray Unit",
    "yanke": "Yankee Unit",
    "yankie": "Yankee Unit",
    "zullu": "Zulu Unit",
    "zulo": "Zulu Unit",
    "perfomanse": "Performance",
    "perfomrnace": "Performance",
    "prefromance": "Performance",
    "performansse": "Performance",
    "performnace": "Performance",
    "leaave": "Leave",
    "leavee": "Leave",
    "medicall": "Medical",
    "medial": "Medical",
    "medicaal": "Medical",
    "attendace": "Attendance",
    "attendanc": "Attendance",
    "atendence": "Attendance",
    "attendence2": "Attendance",
    "verificaion": "Verification",
    "verifiction": "Verification",
    "verifcaation": "Verification",
    "equpiment": "Equipment",
    "equipmennt": "Equipment",
    "eqippment": "Equipment",
    "distirbution": "Distribution",
    "distrbution": "Distribution",
    "distributoin": "Distribution",
    "shedual": "Schedule",
    "schdule": "Schedule",
    "sceduel": "Schedule",
    "to0p": "Top",
    "bottum": "Bottom",
    "bttom": "Bottom",
    "improvment2": "Improvement",
    "improovement": "Improvement",
    "imprvment": "Improvement",
    "dropt": "Drop",
    "droup": "Drop",
    "gradng2": "Grading",
    "graeding": "Grading",
    "avarage": "Average",
    "avareg": "Average",
    "averaage": "Average",
    "disaese": "Disease",
    "diease": "Disease",
    "deseze": "Disease",
    "dizeese": "Disease",
    "diseasse": "Disease",
    "presnet": "Present",
    "presennt": "Present",
    "presernt": "Present",
    "pendeng": "Pending",
    "pendinng": "Pending",
    "pendign2": "Pending",
    "rejeceted": "Rejected",
    "rejeected": "Rejected",
    "rejecetd": "Rejected",
    "retured": "Returned",
    "retuurned": "Returned",
    "reeturned": "Returned",
    "latesst": "Latest",
    "laytest": "Latest",
    "unasssigned": "Unassigned",
    "unassignned": "Unassigned",
    "unnasigned": "Unassigned",
    "runing": "Running",
    "runnin": "Running",
    "runnign": "Running",
    "athletcs": "Athletics",
    "athletiks": "Athletics",
    "athlets": "Athletics",
    "bascketball": "Basketball",
    "baksetball": "Basketball",
    "volybal": "Volleyball",
    "valleyball": "Volleyball",
    "kabaddy": "Kabaddi",
    "kabadhi": "Kabaddi",
    "hocckey": "Hockey",
    "badmintn": "Badminton",
    "batminton": "Badminton",
    "tenniss": "Tennis",
    "table tenis": "Table Tennis",
    "tabletennis": "Table Tennis",
    "table-tenis": "Table Tennis",
    "pingpong": "Table Tennis",
    "ping-pong": "Table Tennis",
    "ping pong": "Table Tennis",
    "swimmig": "Swimming",
    "swimmning": "Swimming",
    "wrestlin": "Wrestling",
    "resstling": "Wrestling",
    "kusti": "Wrestling",
    "khusti": "Wrestling",
    "kushtii": "Wrestling",
    "boxin": "Boxing",
    "bocsing": "Boxing",
    "archary": "Archery",
    "archery": "Archery",
    "archerry": "Archery",
    "shootng": "Shooting",
    "shoting": "Shooting",
    "shootting": "Shooting",
    "weightliftng": "Weightlifting",
    "weigtlifting": "Weightlifting",
    "wieghtlifting": "Weightlifting",
    "gymnastcs": "Gymnastics",
    "jimnastics": "Gymnastics",
    "gymnastis": "Gymnastics",
    "cyclng": "Cycling",
    "cyckling": "Cycling",
    "cycleing": "Cycling",
    "chesss": "Chess",
    "karrom": "Carrom",
    "khokho": "Kho Kho",
    "kho-kho": "Kho Kho",
    "kho kho": "Kho Kho",
    "squas": "Squash",
    "sqash": "Squash",
    "squach": "Squash",
    "biliards": "Billiards",
    "billiard": "Billiards",
    "biliyards": "Billiards",
    "snuker": "Snooker",
    "snokker": "Snooker",
    "snoker": "Snooker",
    "pol": "Pool",
    "pooll": "Pool",
    "judoo": "Judo",
    "joodo": "Judo",
    "karatee": "Karate",
    "karrate": "Karate",
    "caratae": "Karate",
    "taekwondoo": "Taekwondo",
    "tae kwon do": "Taekwondo",
    "taekwondu": "Taekwondo",
    "martial art": "Martial Arts",
    "marshal arts": "Martial Arts",
    "martail arts": "Martial Arts",
    "handbal": "Handball",
    "handball": "Handball",
    "hendball": "Handball",
    "rugbi": "Rugby",
    "ruggby": "Rugby",
    "gholf": "Golf",
    "goolf": "Golf",
    "rowng": "Rowing",
    "rowwing": "Rowing",
    "saling": "Sailing",
    "sailng": "Sailing",
    "fencng": "Fencing",
    "fenceing": "Fencing",
    "equestrain": "Equestrian",
    "equestrien": "Equestrian",
    "ekwestrian": "Equestrian",
    "horse ridding": "Equestrian",
    "horseriding": "Equestrian",
    "horse-riding": "Equestrian",
    "poloo": "Polo",
    "crosscountry": "Cross Country",
    "cross-country": "Cross Country",
    "cros country": "Cross Country",
    "marathn": "Marathon",
    "marathoon": "Marathon",
    "marrathon": "Marathon",
    "5 km": "5km",
    "5-km": "5km",
    "5klm": "5km",
    "5 kilometr": "5km",
    "60 m sprnt": "60m Sprint",
    "60msprint": "60m Sprint",
    "60-m sprint": "60m Sprint",
    "9 ditc": "9' Ditch",
    "9ft ditc": "9' Ditch",
    "nine-ft ditch": "9' Ditch",
    "h-rop": "H Rope",
    "horizental rope": "H Rope",
    "h ropee": "H Rope",
    "v-rop": "V Rope",
    "vertcal rope": "V Rope",
    "v ropee": "V Rope",
    "2.4 km": "2.4km",
    "2,4km": "2.4km",
    "2.4-klm": "2.4km",
    "100msprint": "100m Sprint",
    "100 m sprnt": "100m Sprint",
    "chinup": "Chin Ups",
    "chin-up": "Chin Ups",
    "chinnups": "Chin Ups",
    "situp": "Sit Ups",
    "sit-up": "Sit Ups",
    "situps": "Sit Ups",
    "toetuch": "Toe Touch",
    "toe-tuch": "Toe Touch",
    "toetouches": "Toe Touch",
    "5mshuttle": "5m Shuttle",
    "5-m shuttl": "5m Shuttle",
    "shuttl run": "5m Shuttle",
    "300m5fts": "300m 5 FTS",
    "300 m 5 fts": "300m 5 FTS",
    "200m5fts": "200m 5 FTS",
    "200 m 5 fts": "200m 5 FTS",
    "100mlur": "100m LU (R)",
    "100 m lu r": "100m LU (R)",
    "100mlu5/5": "100m LU (5/5)",
    "100 lu 5by5": "100m LU (5/5)",
    "50msutru": "50m SU TRU",
    "50 su tru": "50m SU TRU",
    "100mnisftsss": "100m NI SFTS SS",
    "100 ni sfts ss": "100m NI SFTS SS",
    "15mbalbc": "15m (Bal) BC",
    "15 bal bc": "15m (Bal) BC",
    "turnout n bearing": "Turn Out and Bearing",
    "turn-out bering": "Turn Out and Bearing",
    "word of comand": "Word of Command",
    "wrd of command": "Word of Command",
    "marchng": "Marching",
    "marchhing": "Marching",
    "slow march": "Slow March",
    "slo march": "Slow March",
    "saluting salami shastr": "Saluting Salami Shastra",
    "turnng": "Turning",
    "turnign": "Turning",
    "pt shoos brown": "Pt Shoes Brown",
    "pt shose brown": "Pt Shoes Brown",
    "cap fs": "Cap FS",
    "capp fs": "Cap FS",
    "mugsteel": "Mug Steel",
    "mug stel": "Mug Steel",
    "blancket": "Blanket",
    "blankett": "Blanket",
    "dms boott gp": "DMS Boot GP",
    "dms bot gp": "DMS Boot GP",
    "terrytowel": "Terry Towel Light Blue",
    "terry towell": "Terry Towel Light Blue",
    "combatt shirt": "Combat T Shirt",
    "combat tshirt": "Combat T Shirt",
    "netmosquito": "Net Mosquito",
    "net moskito": "Net Mosquito",
    "combatt coat": "Combat Coat",
    "combat coatt": "Combat Coat",
    "beltick": "Belt ICK",
    "belt ик": "Belt ICK",
    "belt ic k": "Belt ICK",
    "kitbag": "Kit Bag",
    "kit-bag": "Kit Bag",
    "watter bottle": "Water Bottle Plastic with C",
    "waterbotle": "Water Bottle Plastic with C",
    "jerseyy": "Jersey V Neck",
    "jersy v neck": "Jersey V Neck",
    "sockswoollen": "Socks Woollen OG",
    "socks woolen og": "Socks Woollen OG",
    "trouserdrill": "Trouser Drill Khaki Poly",
    "trousr drill khaki": "Trouser Drill Khaki Poly",

    "performace": "performance",
    "performence": "performance",
    "prefomance": "performance",
    "perfomance": "performance",
    "preformance": "performance",
    "performnce": "performance",
    "attendence": "attendance",
    "attendnce": "attendance",
    "atendance": "attendance",
    "attandance": "attendance",
    "verfication": "verification",
    "verifcation": "verification",
    "verificaton": "verification",
    "varification": "verification",
    "distribtion": "distribution",
    "distributon": "distribution",
    "distibution": "distribution",
    "equipement": "equipment",
    "equiptment": "equipment",
    "equipmnt": "equipment",
    "equpment": "equipment",
    "meical": "medical",
    "medicl": "medical",
    "medcal": "medical",
    "bpet": "bpet",
    "bept": "bpet",
    "betp": "bpet",
    "pptt": "ppt",
    "fiiring": "firing",
    "firng": "firing",
    "fring": "firing",
    "fireing": "firing",
    "drll": "drill",
    "dril": "drill",
    "performrs": "performers",
    "preformers": "performers",
    "perfomers": "performers",
    "bottm": "bottom",
    "lowst": "lowest",
    "loest": "lowest",
    "hihest": "highest",
    "higest": "highest",
    "avrage": "average",
    "averge": "average",
    "avrg": "average",
    "improvment": "improvement",
    "improvemnt": "improvement",
    "improv": "improvement",
    "percentge": "percentage",
    "percntage": "percentage",
    "gradig": "grading",
    "gradng": "grading",
    "gradeing": "grading",
    "sumary": "summary",
    "summry": "summary",
    "attmpt": "attempt",
    "attepmpt": "attempt",
    "atempt": "attempt",
    "attemptwise": "attempt wise",
    "bestattempt": "best attempt",
    "gradingsummary": "grading summary",
    "gradesummary": "grading summary",
    "leeve": "leave",
    "leve": "leave",
    "abscnded": "absconded",
    "absconed": "absconded",
    "presnt": "present",
    "preent": "present",
    "campas": "campus",
    "strenght": "strength",
    "strengh": "strength",
    "montly": "monthly",
    "monthyl": "monthly",
    "overdeu": "overdue",
    "overdu": "overdue",
    "condtion": "condition",
    "conditon": "condition",
    "blod": "blood",
    "bloog": "blood",
    "sportt": "sport",
    "sprot": "sport",
    "classs": "class",
    "claas": "class",
    "todya": "today",
    "todday": "today",
    "persnnel": "person",
    "personel": "person",
    "agniverr": "agniveer",
    "agniver": "agniveer",
    "excelent": "excellent",
    "excellnt": "excellent",
    "satifactory": "satisfactory",
    "unassignd": "unassigned",
    "unasigned": "unassigned",
    "vollyball": "volleyball",
    "voleyball": "volleyball",
    "volyball": "volleyball",
    "criket": "cricket",
    "crciket": "cricket",
    "footbal": "football",
    "footbol": "football",
    "hocky": "hockey",
    "hokey": "hockey",
    "badmintion": "badminton",
    "badminten": "badminton",
    "basaball": "baseball",
    "baskeball": "basketball",
    "baskteball": "basketball",
    "kabadi": "kabaddi",
    "kabbadi": "kabaddi",
}

# =============================================================================
# INTENT TYPE DEFAULTS (VISUALIZATION SUGGESTION - DEPRECATED)
# =============================================================================

# NOTE: These are VISUALIZATION DEFAULTS, which are DEPRECATED per the spec.
# Visualization should be determined AFTER receiving .NET response, not before.
# This is kept for backward compatibility only.

INTENT_TYPE_DEFAULTS: Dict[Tuple[str, str], str] = {
    ("Performance", "Top"): "Tabular",
    ("Performance", "Bottom"): "Tabular",
    ("Performance", "Improvement"): "Trend Chart",
    ("Performance", "Drop"): "Trend Chart",
    ("Performance", "Grading"): "Tabular",
    ("Performance", "GradingSummary"): "Bar Chart",
    ("Performance", "Average"): "Tabular",
    ("Performance", "AttemptWise"): "Tabular",
    ("Performance", "BestAttempt"): "Tabular",
    ("Performance", "Trend"): "Trend Chart",
    ("Leave", "Most"): "Tabular",
    ("Leave", "Least"): "Tabular",
    ("Leave", "Current"): "Tabular",
    ("Leave", "Absconded"): "Tabular",
    ("Leave", "Threshold"): "Tabular",
    ("Medical", "BMI"): "Pie Chart",
    ("Medical", "BloodGroup"): "Tabular",
    ("Medical", "Disease"): "Tabular",
    ("Medical", "Individual"): "Tabular",
    ("Attendance", "Monthly"): "Bar Chart",
    ("Attendance", "Weekly"): "Bar Chart",
    ("Attendance", "Daily"): "Calendar UI",
    ("Attendance", "Present"): "Pie Chart",
    ("Attendance", "Summary"): "Tabular",
    ("Strength", "StrengthBreakdown"): "Line Chart",
    ("Verification", "Pending"): "Tabular",
    ("Verification", "Sent"): "Tabular",
    ("Verification", "NotResponded"): "Tabular",
    ("Verification", "Completed"): "Tabular",
    ("Verification", "Rejected"): "Tabular",
    ("Equipment", "Stats"): "Card",
    ("Equipment", "ByName"): "Tabular",
    ("Equipment", "Returned"): "Tabular",
    ("Equipment", "Holding"): "Tabular",
    ("Equipment", "AgniveerWise"): "Tabular",
    ("Distribution", "Latest"): "Tabular",
    ("Distribution", "ByUnit"): "Tabular",
    ("Distribution", "Unassigned"): "Tabular",
    ("Distribution", "TopUnit"): "Tabular",
    ("Skills", "BySport"): "Tabular",
    ("Skills", "ByClass"): "Tabular",
    ("Overall", "OverallPerformance"): "Tabular",
    ("Schedule", "bytoday"): "Tabular",
    ("Schedule", "bycompany"): "Tabular",
    ("Schedule", "bydate"): "Tabular",
    ("Schedule", "byagniveer"): "Tabular",
}

SUBCATEGORY_TO_OPERATION: Dict[str, str] = {
    "TopPerformers": "Top",
    "LowestPerformers": "Bottom",
    "Improvement": "Improvement",
    "Drop": "Drop",
    "GradeDistribution": "Grading",
    "GradingSummary": "GradingSummary",
    "AverageScore": "Average",
    "AttemptWise": "AttemptWise",
    "BestAttempt": "BestAttempt",
    "Trend": "Trend",
    "TrendAnalysis": "Trend",
    "MostLeaveTaken": "Most",
    "LeastLeaveTaken": "Least",
    "CurrentLeaveStatus": "Current",
    "AbscondedPerson": "Absconded",
    "LeaveType": "LeaveType",
    "Threshold": "Threshold",
    "BMIAnalysis": "BMI",
    "DiseaseStatistics": "Disease",
    "BloodGroup": "BloodGroup",
    "IndividualMedical": "Individual",
    "MonthlyAttendance": "Monthly",
    "WeeklyAttendance": "Weekly",
    "DailyAttendance": "Daily",
    "PresentToday": "Present",
    "AttendanceSummary": "Summary",
    "StrengthBreakdown": "StrengthBreakdown",
    "Strength": "StrengthBreakdown",
    "PendingVerification": "Pending",
    "CompletedVerification": "Completed",
    "NotRespondedVerification": "NotResponded",
    "VerifiedVerification": "Completed",
    "RejectedVerification": "Rejected",
    "SentVerification": "Sent",
    "EquipmentSummary": "Stats",
    "EquipmentSearch": "ByName",
    "Search": "ByName",
    "PoorConditionEquipment": "Returned",
    "ReturnedEquipment": "Returned",
    "HoldingEquipment": "Holding",
    "AgniveerWiseEquipment": "AgniveerWise",
    "LatestDistribution": "Latest",
    "DistributionByUnit": "ByUnit",
    "UnassignedItems": "Unassigned",
    "TopUnit": "TopUnit",
    "BySport": "BySport",
    "ByClass": "ByClass",
    "TodaySchedule": "bytoday",
    "CompanySchedule": "bycompany",
    "DateSchedule": "bydate",
    "AgniveerSchedule": "byagniveer",
    "PersonalDetailInfo": "info",
    "DisqualifiedRemoved": "removed",
    "CompositeRanking": "OverallPerformance",
    "OverallPerformance": "OverallPerformance",
}

OPERATION_TO_PAYLOAD_FIELD: Dict[str, str] = {
    "Top": "Top",
    "Bottom": "Bottom",
    "Improvement": "Improvement",
    "Drop": "Drop",
    "Grading": "Grading",
    "GradingSummary": "GradingSummary",
    "Average": "Average",
    "AttemptWise": "AttemptWise",
    "BestAttempt": "BestAttempt",
    "Most": "Most",
    "Least": "Least",
    "Current": "Current",
    "Absconded": "Absconded",
    "Threshold": "Threshold",
    "BMI": "BMI",
    "BloodGroup": "BloodGroup",
    "Disease": "Disease",
    "Individual": "Individual",
    "Monthly": "Monthly",
    "Weekly": "Weekly",
    "Daily": "Daily",
    "Present": "Present",
    "StrengthBreakdown": "StrengthBreakdown",
    "bytoday": "bytoday",
    "bycompany": "bycompany",
    "bydate": "bydate",
    "byagniveer": "byagniveer",
    "Stats": "Stats",
    "ByName": "ByName",
    "Returned": "Returned",
    "Holding": "Holding",
    "AgniveerWise": "AgniveerWise",
    "Latest": "Latest",
    "ByUnit": "ByUnit",
    "Unassigned": "Unassigned",
    "TopUnit": "TopUnit",
    "BySport": "BySport",
    "ByClass": "ByClass",
    "Pending": "Pending",
    "Sent": "Sent",
    "NotResponded": "NotResponded",
    "Rejected": "Rejected",
    "OverallPerformance": "OverallPerformance",
}

CATEGORY_OPERATION_TO_SUBCATEGORY: Dict[Tuple[str, str], str] = {
    ("Performance", "Top"): "TopPerformers",
    ("Performance", "Bottom"): "LowestPerformers",
    ("Performance", "Improvement"): "Improvement",
    ("Performance", "Drop"): "Drop",
    ("Performance", "Grading"): "GradeDistribution",
    ("Performance", "GradingSummary"): "GradingSummary",
    ("Performance", "Average"): "AverageScore",
    ("Performance", "AttemptWise"): "AttemptWise",
    ("Performance", "BestAttempt"): "BestAttempt",
    ("Performance", "Trend"): "Trend",
    ("Leave", "Most"): "MostLeaveTaken",
    ("Leave", "Least"): "LeastLeaveTaken",
    ("Leave", "Current"): "CurrentLeaveStatus",
    ("Leave", "Absconded"): "AbscondedPerson",
    ("Leave", "LeaveType"): "LeaveType",
    ("Leave", "Threshold"): "Threshold",
    ("Medical", "BMI"): "BMIAnalysis",
    ("Medical", "Disease"): "DiseaseStatistics",
    ("Medical", "BloodGroup"): "BloodGroup",
    ("Medical", "Individual"): "IndividualMedical",
    ("Attendance", "Monthly"): "MonthlyAttendance",
    ("Attendance", "Weekly"): "WeeklyAttendance",
    ("Attendance", "Daily"): "DailyAttendance",
    ("Attendance", "Present"): "PresentToday",
    ("Attendance", "Summary"): "AttendanceSummary",
    ("Strength", "StrengthBreakdown"): "StrengthBreakdown",
    ("Verification", "Pending"): "PendingVerification",
    ("Verification", "Sent"): "SentVerification",
    ("Verification", "NotResponded"): "NotRespondedVerification",
    ("Verification", "Completed"): "CompletedVerification",
    ("Verification", "Verified"): "CompletedVerification",
    ("Verification", "Rejected"): "RejectedVerification",
    ("Equipment", "Stats"): "EquipmentSummary",
    ("Equipment", "ByName"): "EquipmentSearch",
    ("Equipment", "Returned"): "PoorConditionEquipment",
    ("Equipment", "Holding"): "HoldingEquipment",
    ("Equipment", "AgniveerWise"): "AgniveerWiseEquipment",
    ("Distribution", "Latest"): "LatestDistribution",
    ("Distribution", "ByUnit"): "DistributionByUnit",
    ("Distribution", "Unassigned"): "UnassignedItems",
    ("Distribution", "TopUnit"): "TopUnit",
    ("Skills", "BySport"): "BySport",
    ("Skills", "ByClass"): "ByClass",
    ("Overall", "OverallPerformance"): "OverallPerformance",
    ("Schedule", "bytoday"): "TodaySchedule",
    ("Schedule", "bycompany"): "CompanySchedule",
    ("Schedule", "bydate"): "DateSchedule",
    ("Schedule", "byagniveer"): "AgniveerSchedule",
    ("personaldetail", "info"): "PersonalDetailInfo",
    ("disqualified", "removed"): "DisqualifiedRemoved",
}

METADATA: Dict[str, Any] = {
    "responseTypes": RESPONSE_TYPES,
    "responseTypeDefault": RESPONSE_TYPE_DEFAULT,
    "defaultDetailedCategories": DEFAULT_DETAILED_CATEGORIES,
    "detailedKeywords": DETAILED_KEYWORDS,
    "categoryKeywords": CATEGORY_KEYWORDS,
    "operationSynonyms": OPERATION_SYNONYMS,
    "subcategoryToOperation": SUBCATEGORY_TO_OPERATION,
    "categoryOperationToSubcategory": CATEGORY_OPERATION_TO_SUBCATEGORY,
    "intentTypeDefaults": INTENT_TYPE_DEFAULTS,
    "operationToPayloadField": OPERATION_TO_PAYLOAD_FIELD,
}

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def agniveer_no_required(category: Optional[str], operation: Optional[str]) -> bool:
    """Whether this category/operation combination must have an agniveerNo."""
    if not category:
        return False
    if category in AGNIVEER_NO_ALWAYS_REQUIRED_CATEGORIES:
        return True
    exempt_operations = AGNIVEER_NO_REQUIRED_EXCEPT_OPERATIONS.get(category)
    if exempt_operations is not None:
        return operation not in exempt_operations
    return False


def get_section_by_alias(alias: str) -> Optional[str]:
    """Look up section name by alias."""
    alias_lower = str(alias).lower().strip()
    for section_name, section_data in SECTION.items():
        if alias_lower in section_data["aliases"]:
            return section_name
    return None


def is_valid_category(category: str) -> bool:
    """Check if category is in the official list."""
    return category in OFFICIAL_CATEGORIES


def is_valid_operation(category: str, operation: str) -> bool:
    """Check if operation is valid for the given category."""
    if category not in OPERATIONS_BY_CATEGORY:
        return False
    return operation in OPERATIONS_BY_CATEGORY[category]


def get_allowed_entities_for_category(category: str) -> Set[str]:
    """Get all entity types allowed for a category."""
    allowed = COMMON_ENTITY_TYPES.copy()
    if category in CATEGORY_ENTITY_COMPATIBILITY:
        allowed.update(CATEGORY_ENTITY_COMPATIBILITY[category])
    return allowed
